apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: ttl-after-finshed
spec:
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: alpine
        name: ttl-after-finshed
        command: ["echo", "hello"]
        resources: {}
      restartPolicy: Never
status: {}
