apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: weave-scope-app
  namespace: weave
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: scope.sudojoss.com
    http:
      paths:
        - path: /
          backend:
            serviceName: weave-scope-app
            servicePort: 80
  tls: 
  - secretName: sudojoss-tls
    hosts:
    - scope.sudojoss.com
