apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-timber.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag_Regex         (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
        Tag               k8s.<namespace_name>.<pod_name>.<container_name>.<docker_id>-
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               k8s.**
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        K8S-Logging.Parser  On
        Regex_Parser   k8s-custom

  parsers.conf: |
    [PARSER]
        Name         docker
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L
        Time_Keep    On
    [PARSER]
        Name    k8s-custom
        Format  regex
        Regex   ^k8s\.(?<namespace_name>[^_]+)\.(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\.(?<container_name>.+)\.(?<docker_id>[a-z0-9]{64})-$

  output-timber.conf: |
    [OUTPUT]
        Name    http
        Match   k8s.kube-system.nginx-ingress-controller-*
        Host    logs.timber.io
        Port    443
        URI     /sources/${FLUENT_TIMBER_SOURCE_ID}/frames
        Format  msgpack
        Header  Authorization Bearer ${FLUENT_TIMBER_API_KEY}
        Header  Content-Type application/msgpack
        tls     On
    [OUTPUT]
        Name    stdout
        Match   k8s.kube-system.nginx-ingress-controller-*
        Format  msgpack
