kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-0
  labels:
    type: local
spec:
  storageClassName: postgresql
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k8s/postgresql"
