apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-operator
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /opt/k8s/prometheus
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prometheus-operator