kind: PersistentVolume
apiVersion: v1
metadata:
  name: traefik-ingress
  labels:
    type: local
spec:
  storageClassName: traefik-ingress
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k8s/traefik-ingress"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: traefik-ingress
  name: traefik-ingress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: traefik-ingress
  volumeMode: Filesystem
  volumeName: traefik-ingress
status: {}
