apiVersion: v1
kind: PersistentVolume
metadata:
  name: drone
spec:
  storageClassName: drone
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /opt/k8s/drone/drone
  persistentVolumeReclaimPolicy: Retain