apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: prometheus
  name: prometheus-server
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: /opt/k8s/prometheus/prometheus
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prometheus-server
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: prometheus
  name: prometheus-alermanager
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /opt/k8s/prometheus/alertmanager
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prometheus-alertmanager
status: {}
