apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datcom-backend
  labels:
    app: datcom-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: datcom-backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: datcom-backend
          image: jphuc96/datcom_backend:latest
          ports:
            - containerPort: 80
          resources: {}
---
kind: Service
apiVersion: v1
metadata:
  name: datcom-backend
spec:
  selector:
    app: datcom-backend
  ports:
  - name: '80'
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: datcom-backend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # kubernetes.io/tls-acme: "true"
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: datcom.sudojoss.com
    http:
      paths:
        - backend:
            serviceName: datcom-backend
            servicePort: 80
  tls: 
  - secretName: sudojoss-tls
    hosts:
    - datcom.sudojoss.com