apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /opt/k8s/grafana/
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana
status: {}