apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webhook
  name: webhook
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webhook
    spec:
      containers:
      - args:
        - php
        - artisan
        - queue:work
        - --daemon
        - --tries=3
        - --timeout=10
        env:
        - name: APP_DEBUG
          value: "true"
        - name: APP_ENV
          value: dev
        - name: APP_LOG
          value: errorlog
        - name: APP_URL
          value: https://webhook.sudojoss.com
        - name: BROADCAST_DRIVER
          value: redis
        - name: CACHE_DRIVER
          value: redis
        - name: DB_CONNECTION
          value: sqlite
        - name: ECHO_HOST_MODE
          value: path
        - name: QUEUE_DRIVER
          value: redis
        - name: REDIS_HOST
          value: redis-master.default.svc.cluster.local
        image: fredsted/webhook.site
        name: webhook
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: laravel-echo-server
  name: laravel-echo-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: laravel-echo-server
    spec:
      containers:
      - env:
        - name: ECHO_ALLOW_CORS
          value: "true"
        - name: ECHO_ALLOW_HEADERS
          value: '*'
        - name: ECHO_ALLOW_METHODS
          value: '*'
        - name: ECHO_ALLOW_ORIGIN
          value: '*'
        - name: ECHO_PROTOCOL
          value: http
        - name: ECHO_REDIS_HOSTNAME
          value: redis-master.default.svc.cluster.local
        - name: ECHO_REDIS_PORT
          value: "6379"
        - name: LARAVEL_ECHO_SERVER_AUTH_HOST
          value: http://webhook
        - name: LARAVEL_ECHO_SERVER_HOST
          value: 0.0.0.0
        - name: LARAVEL_ECHO_SERVER_PORT
          value: "6001"
        image: mintopia/laravel-echo-server
        name: laravel-echo-server
        ports:
        - containerPort: 6001
        resources: {}
      restartPolicy: Always
status: {}
