---
# Source: gocd/templates/gocd-ea-service-account.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: gocd
  labels:
    chart: "gocd-1.13.0"
    app: "gocd"
    heritage: "Tiller"
    release: "gocd"

