---
# Source: gocd/templates/gocd-server-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocd-server
  labels:
    app: gocd
    chart: "gocd-1.13.0"
    release: "gocd"
    heritage: "Tiller"
    component: server
  annotations:
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gocd
      release: "gocd"
      component: server
  template:
    metadata:
      labels:
        app: gocd
        release: "gocd"
        component: server
      annotations:
    spec:
      serviceAccountName: gocd
      volumes:
        - name: config-vol
          configMap:
            name: gocd
        - name: goserver-vol
          persistentVolumeClaim:
            claimName: gocd-server
      containers:
        - name: gocd-server
          image: "gocd/gocd-server:v19.5.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: GOCD_PLUGIN_INSTALL_kubernetes-elastic-agents
              value: https://github.com/gocd/kubernetes-elastic-agents/releases/download/v3.0.0-156/kubernetes-elastic-agent-3.0.0-156.jar
            - name: GOCD_PLUGIN_INSTALL_docker-registry-artifact-plugin
              value: https://github.com/gocd/docker-registry-artifact-plugin/releases/download/v1.1.0-104/docker-registry-artifact-plugin-1.1.0-104.jar
            
          ports:
            - containerPort: 8153
            - containerPort: 8154
          livenessProbe:
            httpGet:
              path: /go/api/v1/health
              port: 8153
            initialDelaySeconds: 90
            periodSeconds: 15
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /go/api/v1/health
              port: 8153
            initialDelaySeconds: 90
            periodSeconds: 15
            failureThreshold: 10
          volumeMounts:
            - name: config-vol
              mountPath: /preconfigure_server.sh
              subPath: preconfigure_server.sh
            - name: goserver-vol
              mountPath: /godata
              subPath: godata
            - name: goserver-vol
              mountPath: /home/go
              subPath: homego
            - name: goserver-vol
              mountPath: /docker-entrypoint.d
              subPath: scripts
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/bash
                  - /preconfigure_server.sh
                  
          resources:
            {}
            
      restartPolicy: Always
