apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-operator-alertmanager
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /opt/k8s/prometheus-operator/alertmanager
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prometheus-operator-alertmanager
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-operator-prometheus
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /opt/k8s/prometheus-operator/prometheus
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prometheus-operator-prometheus
