apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-06-28T08:00:25Z"
  generation: 1
  labels:
    app: gitlab-runner-gitlab-runner
    chart: gitlab-runner-0.6.0
    heritage: Tiller
    release: gitlab-runner
  name: gitlab-runner-gitlab-runner
  namespace: gitlab-runner
  resourceVersion: "4473985"
  selfLink: /apis/apps/v1/namespaces/gitlab-runner/deployments/gitlab-runner-gitlab-runner
  uid: c91ced4a-997a-11e9-a7cb-0cc47a037588
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: gitlab-runner-gitlab-runner
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/configmap: 838318240391c55d6c87ad6e17592d5f84a69271f3ba6d7e0530db66460ce470
        checksum/secrets: ccb50de823931f9212be96c1d86b5aaa641d6dffab47cbf8886c65a631ff938d
      creationTimestamp: null
      labels:
        app: gitlab-runner-gitlab-runner
    spec:
      containers:
      - command:
        - /bin/bash
        - /scripts/entrypoint
        env:
        - name: CI_SERVER_URL
          value: https://git.d.foundation/
        - name: CLONE_URL
        - name: RUNNER_REQUEST_CONCURRENCY
          value: "1"
        - name: RUNNER_EXECUTOR
          value: kubernetes
        - name: REGISTER_LOCKED
          value: "false"
        - name: RUNNER_TAG_LIST
        - name: KUBERNETES_IMAGE
          value: docker:18
        - name: KUBERNETES_PRIVILEGED
          value: "true"
        - name: KUBERNETES_NAMESPACE
          value: gitlab-runner
        - name: KUBERNETES_CPU_LIMIT
          value: 500m
        - name: KUBERNETES_MEMORY_LIMIT
          value: 512Mi
        - name: KUBERNETES_CPU_REQUEST
        - name: KUBERNETES_MEMORY_REQUEST
        - name: KUBERNETES_SERVICE_ACCOUNT
        - name: KUBERNETES_SERVICE_CPU_LIMIT
          value: 200m
        - name: KUBERNETES_SERVICE_MEMORY_LIMIT
          value: 256Mi
        - name: KUBERNETES_SERVICE_CPU_REQUEST
        - name: KUBERNETES_SERVICE_MEMORY_REQUEST
        - name: KUBERNETES_HELPER_CPU_LIMIT
          value: 200m
        - name: KUBERNETES_HELPER_MEMORY_LIMIT
          value: 256Mi
        - name: KUBERNETES_HELPER_CPU_REQUEST
        - name: KUBERNETES_HELPER_MEMORY_REQUEST
        - name: KUBERNETES_HELPER_IMAGE
        - name: KUBERNETES_PULL_POLICY
        - name: CACHE_TYPE
          value: gcs
        - name: CACHE_PATH
          value: cached
        - name: CACHE_SHARED
          value: "true"
        - name: CACHE_GCS_BUCKET_NAME
          value: dwarvesf-gitlab-runner
        image: gitlab/gitlab-runner:alpine-v11.11.3
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - gitlab-runner
              - unregister
              - --all-runners
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - /scripts/check-live
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: gitlab-runner-gitlab-runner
        ports:
        - containerPort: 9252
          name: metrics
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/bin/pgrep
            - gitlab.*runner
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets
          name: runner-secrets
        - mountPath: /home/gitlab-runner/.gitlab-runner
          name: etc-gitlab-runner
        - mountPath: /scripts
          name: scripts
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - /config/configure
        env:
        - name: CI_SERVER_URL
          value: https://git.d.foundation/
        - name: CLONE_URL
        - name: RUNNER_REQUEST_CONCURRENCY
          value: "1"
        - name: RUNNER_EXECUTOR
          value: kubernetes
        - name: REGISTER_LOCKED
          value: "false"
        - name: RUNNER_TAG_LIST
        - name: KUBERNETES_IMAGE
          value: docker:18
        - name: KUBERNETES_PRIVILEGED
          value: "true"
        - name: KUBERNETES_NAMESPACE
          value: gitlab-runner
        - name: KUBERNETES_CPU_LIMIT
          value: 500m
        - name: KUBERNETES_MEMORY_LIMIT
          value: 512Mi
        - name: KUBERNETES_CPU_REQUEST
        - name: KUBERNETES_MEMORY_REQUEST
        - name: KUBERNETES_SERVICE_ACCOUNT
        - name: KUBERNETES_SERVICE_CPU_LIMIT
          value: 200m
        - name: KUBERNETES_SERVICE_MEMORY_LIMIT
          value: 256Mi
        - name: KUBERNETES_SERVICE_CPU_REQUEST
        - name: KUBERNETES_SERVICE_MEMORY_REQUEST
        - name: KUBERNETES_HELPER_CPU_LIMIT
          value: 200m
        - name: KUBERNETES_HELPER_MEMORY_LIMIT
          value: 256Mi
        - name: KUBERNETES_HELPER_CPU_REQUEST
        - name: KUBERNETES_HELPER_MEMORY_REQUEST
        - name: KUBERNETES_HELPER_IMAGE
        - name: KUBERNETES_PULL_POLICY
        - name: CACHE_TYPE
          value: gcs
        - name: CACHE_PATH
          value: cached
        - name: CACHE_SHARED
          value: "true"
        - name: CACHE_GCS_BUCKET_NAME
          value: dwarvesf-gitlab-runner
        image: gitlab/gitlab-runner:alpine-v11.11.3
        imagePullPolicy: IfNotPresent
        name: configure
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets
          name: runner-secrets
        - mountPath: /config
          name: scripts
          readOnly: true
        - mountPath: /init-secrets
          name: init-runner-secrets
          readOnly: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65533
        runAsUser: 100
      serviceAccount: gitlab-runner-gitlab-runner
      serviceAccountName: gitlab-runner-gitlab-runner
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: runner-secrets
      - emptyDir:
          medium: Memory
        name: etc-gitlab-runner
      - name: init-runner-secrets
        projected:
          defaultMode: 420
          sources:
          - secret:
              name: google-application-credentials
          - secret:
              items:
              - key: runner-registration-token
                path: runner-registration-token
              - key: runner-token
                path: runner-token
              name: gitlab-runner-gitlab-runner
      - configMap:
          defaultMode: 420
          name: gitlab-runner-gitlab-runner
        name: scripts
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-06-28T08:00:25Z"
    lastUpdateTime: "2019-06-28T08:00:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
