apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sudojoss
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sudojoss
    spec:
      containers:
        - name: sudojoss
          image: jphuc96/sudojoss-landing-page:latest
#          imagePullPolicy: Never
          # args:
          ports:
            - containerPort: 8081
          resources: {}
---
kind: Service
apiVersion: v1
metadata:
  name: sudojoss
spec:
  selector:
    app: sudojoss
  ports:
  - name: '8081'
    port: 8081
    targetPort: 8081
