apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: sudojoss
  name: sudojoss
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /opt/k8s/sudojoss/
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sudojoss
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sudojoss
  name: sudojoss
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: sudojoss
  volumeMode: Filesystem
status: {}