apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grav
  labels:
    app: grav
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grav
    spec:
      restartPolicy: Always
      containers:
        - name: grav
          image: jphuc96/grav:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          volumeMounts:
          - mountPath: /var/www/html
            name: data
      volumes:
      - name: data 
        persistentVolumeClaim:
          claimName: grav
