apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grav
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: grav.sudojoss.com
    http:
      paths:
        - path: /
          backend:
            serviceName: grav
            servicePort: 80
  tls: 
  - secretName: sudojoss-tls
    hosts:
    - grav.sudojoss.com
