kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k8s/mysql/data"