apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ghost
  name: ghost-content
spec:
  storageClassName: ghost-content
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ghost-db
  name: ghost-db
spec:
  storageClassName: ghost-db
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
