kind: Service
apiVersion: v1
metadata:
 name: external-node-red
spec:
 type: ClusterIP
 ports:
 - port: 1880
   targetPort: 1880
---
kind: Endpoints
apiVersion: v1
metadata:
 name: external-node-red
subsets:
 - addresses:
     - ip: 192.168.0.6
   ports:
     - port: 1880
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: external-node-red
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: node-red
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - NodeRed"
spec:
  rules:
  - host: test.sudojoss.com
    http:
      paths:
        - path: /
          backend:
            serviceName: external-node-red
            servicePort: 1880
  tls: 
  - secretName: sudojoss-tls
    hosts:
    - test.sudojoss.com