kind: Service
apiVersion: v1
metadata:
 name: portainer
spec:
 type: ClusterIP
 ports:
 - port: 80
   targetPort: 80
---
kind: Endpoints
apiVersion: v1
metadata:
 name: portainer
subsets:
 - addresses:
     - ip: 192.168.0.6
   ports:
     - port: 9000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: portainer
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: www.sudojoss.com
    http:
      paths:
        - path: /
          backend:
            serviceName: portainer
            servicePort: 80
  tls: 
  - secretName: sudojoss-tls
    hosts:
    - test.sudojoss.com