apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongo_rootpasswd
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        image: mongo:latest
        name: mongo
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongo-claim0
        - mountPath: /data/configdb
          name: mongo-claim1
      restartPolicy: Always
      volumes:
      - name: mongo-claim0
        persistentVolumeClaim:
          claimName: mongo-claim0
      - name: mongo-claim1
        persistentVolumeClaim:
          claimName: mongo-claim1
status: {}
