kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis
  labels:
    type: local
spec:
  storageClassName: redis
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k8s/redis"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#     app: redis
#   name: redis
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 8Gi
#   storageClassName: redis
#   volumeMode: Filesystem
#   volumeName: redis
# status: {}